import { body, param, query, ValidationChain } from 'express-validator';

export const validateChat = (): ValidationChain[] => [
  body('agentType')
    .trim()
    .notEmpty()
    .withMessage('Agent type is required')
    .isIn(['resident-assistant', 'committee-advisor', 'financial-analyst', 'compliance-monitor'])
    .withMessage('Invalid agent type'),

  body('message')
    .trim()
    .notEmpty()
    .withMessage('Message is required')
    .isLength({ min: 1, max: 5000 })
    .withMessage('Message must be between 1 and 5000 characters'),

  body('conversationId')
    .optional()
    .isMongoId()
    .withMessage('Invalid conversation ID'),

  body('societyId')
    .trim()
    .notEmpty()
    .withMessage('Society ID is required')
    .isMongoId()
    .withMessage('Invalid Society ID'),
];

export const validateGetConversations = (): ValidationChain[] => [
  query('page')
    .optional()
    .isInt({ min: 1 })
    .withMessage('Page must be a positive integer'),

  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('Limit must be between 1 and 100'),

  query('status')
    .optional()
    .isIn(['active', 'archived'])
    .withMessage('Invalid status'),

  query('agentType')
    .optional()
    .isIn(['resident-assistant', 'committee-advisor', 'financial-analyst', 'compliance-monitor'])
    .withMessage('Invalid agent type'),

  query('sortBy')
    .optional()
    .isIn(['lastMessageAt', 'createdAt', 'messageCount'])
    .withMessage('Invalid sort field'),

  query('sortOrder')
    .optional()
    .isIn(['asc', 'desc'])
    .withMessage('Sort order must be asc or desc'),
];

export const validateConversationId = (): ValidationChain[] => [
  param('id')
    .isMongoId()
    .withMessage('Invalid conversation ID'),
];

export const validateGetInsights = (): ValidationChain[] => [
  query('page')
    .optional()
    .isInt({ min: 1 })
    .withMessage('Page must be a positive integer'),

  query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('Limit must be between 1 and 100'),

  query('insightType')
    .optional()
    .isIn(['prediction', 'anomaly', 'recommendation', 'trend', 'alert'])
    .withMessage('Invalid insight type'),

  query('category')
    .optional()
    .isIn(['financial', 'complaints', 'members', 'maintenance', 'compliance', 'general'])
    .withMessage('Invalid category'),

  query('severity')
    .optional()
    .isIn(['info', 'low', 'medium', 'high', 'critical'])
    .withMessage('Invalid severity'),

  query('isActive')
    .optional()
    .isBoolean()
    .withMessage('isActive must be a boolean'),

  query('sortBy')
    .optional()
    .isIn(['createdAt', 'severity', 'insightType', 'category'])
    .withMessage('Invalid sort field'),

  query('sortOrder')
    .optional()
    .isIn(['asc', 'desc'])
    .withMessage('Sort order must be asc or desc'),
];

export const validateCreateInsight = (): ValidationChain[] => [
  body('societyId')
    .trim()
    .notEmpty()
    .withMessage('Society ID is required')
    .isMongoId()
    .withMessage('Invalid Society ID'),

  body('insightType')
    .trim()
    .notEmpty()
    .withMessage('Insight type is required')
    .isIn(['prediction', 'anomaly', 'recommendation', 'trend', 'alert'])
    .withMessage('Invalid insight type'),

  body('category')
    .trim()
    .notEmpty()
    .withMessage('Category is required')
    .isIn(['financial', 'complaints', 'members', 'maintenance', 'compliance', 'general'])
    .withMessage('Invalid category'),

  body('title')
    .trim()
    .notEmpty()
    .withMessage('Title is required')
    .isLength({ min: 3, max: 200 })
    .withMessage('Title must be between 3 and 200 characters'),

  body('description')
    .trim()
    .notEmpty()
    .withMessage('Description is required')
    .isLength({ min: 10, max: 5000 })
    .withMessage('Description must be between 10 and 5000 characters'),

  body('severity')
    .optional()
    .isIn(['info', 'low', 'medium', 'high', 'critical'])
    .withMessage('Invalid severity'),

  body('data')
    .optional()
    .isObject()
    .withMessage('Data must be an object'),

  body('actionable')
    .optional()
    .isBoolean()
    .withMessage('Actionable must be a boolean'),

  body('actionUrl')
    .optional()
    .isString()
    .trim()
    .withMessage('Action URL must be a string'),

  body('expiresAt')
    .optional()
    .isISO8601()
    .withMessage('Invalid expiry date format')
    .toDate(),

  body('generatedBy')
    .optional()
    .isString()
    .trim()
    .withMessage('Generated by must be a string'),
];

export const validateInsightId = (): ValidationChain[] => [
  param('id')
    .isMongoId()
    .withMessage('Invalid insight ID'),
];

export const validateGetDashboardInsights = (): ValidationChain[] => [
  query('societyId')
    .trim()
    .notEmpty()
    .withMessage('Society ID is required')
    .isMongoId()
    .withMessage('Invalid Society ID'),
];
